Fix/NEX-2149/Fix testMap properties
oat-sa/extension-tao-testqti-previewer pull request #104
Opened 2020-10-22 09:52 UTC by shpran

Relates to: [NEX-2149](https://oat-sa.atlassian.net/browse/NEX-2149)

**Changes:**
* configure test previewer to check `is item informational`;
* use title of the item as label.

2020-10-22 10:24 UTC, bziondik approved these changes
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2020-10-23 06:23 UTC, SergiiTao requested changes
minor cs issues

2020-10-23 06:23 UTC, SergiiTao commented on models/test/mapper/TestPreviewMapper.php
>                  if ($checkInformational) {
please rename this var. the current name is confusing.

2020-10-23 06:23 UTC, SergiiTao commented on models/test/mapper/TestPreviewMapper.php
> +                    $isItemInformational = in_array(
please remove //TODO stub and move this check to the private method

2020-10-23 06:23 UTC, SergiiTao commented on controller/TestPreviewer.php
> +                ->createPreview(new TestPreviewRequest($requestParams['testUri'], new TestPreviewConfig([
align the code please

2020-10-23 07:55 UTC, merged