Fix/tr 663 disable submit plugin on review
oat-sa/extension-tao-testqti-previewer pull request #119
Opened 2021-03-02 09:55 UTC by btamas

2021-03-02 15:23 UTC, jsconan requested changes
It works well, but it might not if a view alias is used instead of the final view renderer name.
Of course, for the results review, it will be ok. But not sure it will if the component is included from other places.

2021-03-02 16:32 UTC, btamas commented on views/js/previewer/plugins/navigation/submit/submit.js
> +                return !config.options.readOnly && config.options.view !== "reviewRenderer";
Thank you for the solution. When I've written down `"reviewRenderer"`, I had a feeling I could do it better. Next time I will listen to it and go deeper.

2021-03-02 17:25 UTC, jsconan approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2021-03-03 07:36 UTC, meefox approved these changes

2021-03-03 15:10 UTC, merged