Feature/AUT-1778/introduce allow skiping attribute on items
oat-sa/extension-tao-testqti-previewer pull request #155
Opened 2022-01-19 09:17 UTC by bziondik

Related to: https://oat-sa.atlassian.net/browse/AUT-1778

How to test:

- set in test Authoring Allow Skipping checkbox for items
- save
- go to Item Preview
- skip items with Allow Skipping without responding to them

2022-01-19 09:25 UTC, bartlomiejmarszal reviewed
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2022-01-20 14:07 UTC, bartlomiejmarszal requested changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2022-01-20 14:07 UTC, bartlomiejmarszal commented on models/test/mapper/TestPreviewMapper.php
> +                    'allowSkipping' => $itemRef->getItemSessionControl()->doesAllowSkipping()
This variable should be added to `\oat\taoQtiTestPreviewer\test\unit\models\test\factory\TestPreviewMapperTest`

2022-01-20 17:05 UTC, Silvia-loza reviewed
LGTM and works fine in local with terre test preview, however throws error when changing config to solar preview. 
![image](https://user-images.githubusercontent.com/60346520/150386382-e862d9ad-1c50-4452-b096-56911ddbb79e.png)
![image](https://user-images.githubusercontent.com/60346520/150386557-a459ab1d-97b2-41b1-9964-156c33dfffc4.png)

2022-01-24 10:48 UTC, Silvia-loza approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X]  Pull request's target is not` master`
- [X] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

2022-01-25 07:48 UTC, bartlomiejmarszal reviewed
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2022-01-25 07:48 UTC, bartlomiejmarszal approved these changes
LGTM

2022-01-25 09:59 UTC, AntonNeviarouski commented
QA verified

2022-01-25 10:07 UTC, merged